/* eslint-env mocha */
import { chai, expect }	from 'meteor/practicalmeteor:chai'; chai.should();
import { cleanAddress, odooParseShipAddress }	from './odooParse.js';



const test_data = [
{ ref: 'SO101907', addr: 'Rococo Hair Design, Windsor Road, Kellyville NSW, Australia', inst: '2/64 Windsor Rd, Kellyville NSW 2155, Australia',
		 result: 'Rococo Hair Design, 2/64 Windsor Rd, Kellyville NSW 2155' },
{ ref: 'SO101906', addr: '1 Rivett Rd, North Ryde NSW 2113, Australia', inst: 'Building A, 3M Australia',
		 result: '1 Rivett Rd, North Ryde NSW 2113' },
{ ref: 'SO101902', addr: 'AGL Energy, George Street, Sydney NSW, Australia', inst: 'Lvl 24, 200 George St, Sydney NSW 2000, Australia',
		 result: 'AGL Energy, Lvl 24, 200 George St, Sydney NSW 2000' },
{ ref: 'SO101901', addr: 'Hachette Australia Books, Kent Street, Sydney NSW, Australia', inst: '17/207 Kent St, Sydney NSW 2000, Australia',
		 result: 'Hachette Australia Books, 17/207 Kent St, Sydney NSW 2000' },
{ ref: 'SO101898', addr: 'GroupM, 65 Berry Street, North Sydney NSW, Australia', inst: '11/65 Berry St, North Sydney NSW 2060, Australia',
		 result: 'GroupM, 11/65 Berry St, North Sydney NSW 2060' },
{ ref: 'SO101884', addr: 'Piper Alderman, Sydney NSW, Australia', inst: 'Level 23, Governor Macquarie Tower, 1 Farrer Place, Sydney NSW 2000, Australia',
		 result: 'Piper Alderman, Level 23, Governor Macquarie Tower, 1 Farrer Pl, Sydney NSW 2000' },
{ ref: 'SO101880', addr: 'Adobe, Sussex Street, Sydney NSW, Australia', inst: 'Level 27, Tower 2, Darling Park, 201 Sussex St, Sydney NSW 2000, Australia',
		 result: 'Adobe, Level 27, Tower 2, Darling Park, 201 Sussex St, Sydney NSW 2000' },
{ ref: 'SO101861', addr: 'Liberty Signs, Rodborough Road, Frenchs Forest NSW, Australia', inst: '1/14 Rodborough Rd, Frenchs Forest NSW 2086, Australia',
		 result: 'Liberty Signs, 1/14 Rodborough Rd, Frenchs Forest NSW 2086' },
{ ref: 'SO101858', addr: 'TEG Live, Liverpool Street, Sydney NSW, Australia', inst: 'level 3/175 Liverpool St, Sydney NSW 2001, Australia',
		 result: 'TEG Live, level 3/175 Liverpool St, Sydney NSW 2001' },
{ ref: 'SO101836', addr: 'BresicWhitney, Liverpool Street, Darlinghurst NSW, Australia', inst: '2, 318 Liverpool St, Darlinghurst NSW 2010, Australia',
		 result: 'BresicWhitney, 2, 318 Liverpool St, Darlinghurst NSW 2010' },
{ ref: 'SO101832', addr: 'Royal Far West, South Steyne, Manly NSW, Australia', inst: '19/21 S Steyne, Manly NSW 2095, Australia',
		 result: 'Royal Far West, South Steyne, 19/21 S Steyne, Manly NSW 2095' },
{ ref: 'SO101826', addr: 'Wolper Jewish Hospital, 8 Trelawney Street, Woollahra NSW, Australia', inst: 'Room 48, 8 Trelawney St, Woollahra NSW 2025, Australia',
		 result: 'Wolper Jewish Hospital, Room 48, 8 Trelawney St, Woollahra NSW 2025' },
{ ref: 'SO101811', addr: 'Pier One Sydney Harbour, Autograph Collection, Sydney NSW, Australia', inst: '11 Hickson Road Walsh Bay, Sydney NSW 2000, Australia',
		 result: 'Pier One Sydney Harbour, Autograph Collection, 11 Hickson Rd Walsh Bay, Sydney NSW 2000' },
{ ref: 'SO101810', addr: 'Decorative Events & Exhibitions, Coward Street, Mascot NSW, Australia', inst: '286 Coward St, Mascot NSW 2020, Australia',
		 result: 'Decorative Events & Exhibitions, 286 Coward St, Mascot NSW 2020' },
{ ref: 'SO101793', addr: 'Opera Australia, 480 Elizabeth St, Surry Hills NSW, Australia', inst: '480 Elizabeth St, Surry Hills NSW 2010, Australia',
		 result: 'Opera Australia, 480 Elizabeth St, Surry Hills NSW 2010' },
{ ref: 'SO101786', addr: 'Slater and Gordon Lawyers, Market Street, Sydney NSW, Australia', inst: '44 Market St, Sydney NSW 2000, Australia',
		 result: 'Slater and Gordon Lawyers, 44 Market St, Sydney NSW 2000' },
{ ref: 'SO101777', addr: 'Turner Freeman Lawyers, George Street, Parramatta NSW, Australia', inst: '8/100 George St, Parramatta NSW 2150, Australia',
		 result: 'Turner Freeman Lawyers, 8/100 George St, Parramatta NSW 2150' },
{ ref: 'SO101759', addr: 'BT Financial Group, Barangaroo Avenue, Barangaroo NSW, Australia', inst: 'Level 13, Tower Two International Towers, 200, Barangaroo Avenue, Barangaroo NSW 2000, Australia',
		 result: 'BT Financial Group, Level 13, Tower Two International Towers, 200, Barangaroo Ave, Barangaroo NSW 2000' },
{ ref: 'SO101754', addr: 'Wotton + Kearney, Castlereagh Street, Sydney NSW, Australia', inst: 'F26, 85 Castlereagh St, Sydney NSW 2000, Australia',
		 result: 'Wotton + Kearney, F26, 85 Castlereagh St, Sydney NSW 2000' },
{ ref: 'SO101752', addr: 'Johnson Winter & Slattery, Bond Street, Sydney NSW, Australia', inst: 'Level 25/20 Bond St, Sydney NSW 2000, Australia',
		 result: 'Johnson Winter & Slattery, Level 25/20 Bond St, Sydney NSW 2000' },
{ ref: 'SO101748', addr: 'Aussie Home Loans Neutral Bay, Military Road, Neutral Bay NSW, Australia', inst: 'Shop 3/115 Military Rd, Neutral Bay NSW 2089, Australia',
		 result: 'Aussie Home Loans Neutral Bay, Shop 3/115 Military Rd, Neutral Bay NSW 2089' },
{ ref: 'SO101734', addr: 'Studio 500 Hair & Beauty, Miller Street, Cammeray NSW, Australia', inst: '445 Miller St, Cammeray NSW 2062, Australia',
		 result: 'Studio 500 Hair & Beauty, 445 Miller St, Cammeray NSW 2062' },
{ ref: 'SO101727', addr: 'Royal Prince Alfred Hospital, Missenden Road, Camperdown NSW, Australia', inst: '50 Missenden Rd, Camperdown NSW 2050, Australia',
		 result: 'Royal Prince Alfred Hospital, 50 Missenden Rd, Camperdown NSW 2050' },
{ ref: 'SO101725', addr: 'Colliers International, George Street, Sydney NSW, Australia', inst: '30, 225 George St, Sydney NSW 2000, Australia',
		 result: 'Colliers International, 30, 225 George St, Sydney NSW 2000' },
{ ref: 'SO101721', addr: '7 Barker Street, Randwick NSW, Australia', inst: 'Prince of Wales Private Hospital, Ward 6 north - room 649 - Barker St, Randwick NSW 2031, Australia',
		 result: '7 Barker St, Prince of Wales Private Hospital, Ward 6 north - room 649 - Barker St, Randwick NSW 2031' },
{ ref: 'SO101713', addr: 'Raine & Horne HM Group, Alexander Street, Crows Nest NSW, Australia', inst: 'g02/99 Alexander St, Crows Nest NSW 2065, Australia',
		 result: 'Raine & Horne HM Group, g02/99 Alexander St, Crows Nest NSW 2065' },
{ ref: 'SO101699', addr: 'Mental Health Review Tribunal, Gladesville NSW, Australia', inst: 'Building 40, Digby Road, Gladesville NSW 2111, Australia',
		 result: 'Mental Health Review Tribunal, Building 40, Digby Rd, Gladesville NSW 2111' },
{ ref: 'SO101697', addr: 'Qi Health & Yoga, The Corso, Manly NSW, Australia', inst: '1/9 The Corso, Manly NSW 2095, Australia',
		 result: 'Qi Health & Yoga, 1/9 The Corso, Manly NSW 2095' },
{ ref: 'SO101691', addr: 'Zimmer Australia, Narabang Way, Belrose NSW, Australia', inst: '4, 12 Narabang Way, Belrose NSW 2085, Australia',
		 result: 'Zimmer Australia, 4, 12 Narabang Way, Belrose NSW 2085' },
{ ref: 'SO101689', addr: 'Gadens, Sydney NSW, Australia', inst: 'Level 40, Gateway, 1 Macquarie Place, Sydney NSW 2000, Australia',
		 result: 'Gadens, Level 40, Gateway, 1 Macquarie Pl, Sydney NSW 2000' },
{ ref: 'SO101685', addr: 'Wahroonga Adventist School, 181 Fox Valley Road, Wahroonga NSW, Australia', inst: '181 Fox Valley Rd, Wahroonga NSW 2076, Australia',
		 result: 'Wahroonga Adventist School, 181 Fox Valley Rd, Wahroonga NSW 2076' },
{ ref: 'SO101680', addr: 'CAMILLA AND MARC Head Office, Young Street, Waterloo NSW, Australia', inst: '291 Young St, Waterloo NSW 2017, Australia',
		 result: 'CAMILLA AND MARC Head Office, 291 Young St, Waterloo NSW 2017' },
{ ref: 'SO101676', addr: 'Royal North Shore Hospital, Reserve Road, St Leonards NSW, Australia', inst: 'Reserve Rd, St Leonards NSW 2065, Australia',
		 result: 'Royal North Shore Hospital, Reserve Rd, St Leonards NSW 2065' },
{ ref: 'SO101670', addr: 'FCB Group, Mount Street, North Sydney NSW, Australia', inst: 'Level 11, 83 Mount St, North Sydney NSW 2060, Australia',
		 result: 'FCB Group, Level 11, 83 Mount St, North Sydney NSW 2060' },
{ ref: 'SO101663', addr: 'Aspect Designs, Crows Nest NSW, Australia', inst: 'suite 103 84Alexander St, Crows Nest NSW 2065, Australia',
		 result: 'Aspect Designs, suite 103 84Alexander St, Crows Nest NSW 2065' },
{ ref: 'SO101662', addr: 'Banco Chambers, Chifley Tower, Chifley Square, Sydney NSW, Australia', inst: '9, Chifley Tower, 2 Chifley Square, Sydney NSW 2000, Australia',
		 result: 'Banco Chambers, 9, Chifley Tower, 2 Chifley Square, Sydney NSW 2000' },
{ ref: 'SO101661', addr: 'Cards Only Pty Ltd, Leighton Place, Hornsby NSW, Australia', inst: '6/26 Leighton Pl, Hornsby NSW 2077, Australia',
		 result: 'Cards Only Pty Ltd, 6/26 Leighton Pl, Hornsby NSW 2077' },
{ ref: 'SO101644', addr: 'Hotel Employers Mutual, 345, George Street, Sydney NSW 2000, Australia', inst: 'Level 3/345 George St, Sydney NSW 2000, Australia',
		 result: 'Hotel Employers Mutual, Level 3/345 George St, Sydney NSW 2000' },
{ ref: 'SO101625', addr: 'The Parlour Room, Clovelly Road, Randwick NSW, Australia', inst: '216 Clovelly Rd, Randwick NSW 2031, Australia',
		 result: 'The Parlour Room, 216 Clovelly Rd, Randwick NSW 2031' },
{ ref: 'SO101621', addr: 'Val Morgan, George Street, Sydney NSW, Australia', inst: '50, 680 George St, Sydney NSW 2000, Australia',
		 result: 'Val Morgan, 50, 680 George St, Sydney NSW 2000' },
{ ref: 'SO101583', addr: 'Mckinsey & Co, Phillip Street, Sydney NSW, Australia', inst: '35/88 Phillip St, Sydney NSW 2000, Australia',
		 result: 'Mckinsey & Co, 35/88 Phillip St, Sydney NSW 2000' },
{ ref: 'SO101574', addr: 'UTS Insearch, Thomas Street, Haymarket NSW, Australia', inst: '187 Thomas St, Haymarket NSW 2000, Australia',
		 result: 'UTS Insearch, 187 Thomas St, Haymarket NSW 2000' },
{ ref: 'SO101573', addr: 'Bell Shakespeare, Playfair Street, The Rocks NSW, Australia', inst: 'level 1/33 Playfair St, The Rocks NSW 2000, Australia',
		 result: 'Bell Shakespeare, level 1/33 Playfair St, The Rocks NSW 2000' },
{ ref: 'SO101569', addr: 'Richard Crookes Constructions, Broadcast Way, Artarmon NSW, Australia', inst: 'Level 3/4 Broadcast Way, Artarmon NSW 2064, Australia',
		 result: 'Richard Crookes Constructions, Level 3/4 Broadcast Way, Artarmon NSW 2064' },
{ ref: 'SO101567', addr: 'News Corp Australia, Holt Street, Surry Hills NSW, Australia', inst: '2 Holt St, Surry Hills NSW 2010, Australia',
		 result: 'News Corp Australia, 2 Holt St, Surry Hills NSW 2010' },
{ ref: 'SO101553', addr: 'Blu Creativity, Liverpool Street, Sydney NSW, Australia', inst: '39 Liverpool St, Sydney NSW 2000, Australia',
		 result: 'Blu Creativity, 39 Liverpool St, Sydney NSW 2000' },
{ ref: 'SO101550', addr: 'Gordon Private Hospital, Pacific Highway, Gordon NSW, Australia', inst: '748 Pacific Hwy, Gordon NSW 2072, Australia',
		 result: 'Gordon Private Hospital, 748 Pacific Hwy, Gordon NSW 2072' },
{ ref: 'SO101546', addr: 'Thai Airways International, Pitt Street, Sydney NSW, Australia', inst: '75 Pitt St, Sydney NSW 2000, Australia',
		 result: 'Thai Airways International, 75 Pitt St, Sydney NSW 2000' },
{ ref: 'SO101545', addr: 'LinkedIn Sydney, Martin Place, Sydney NSW, Australia', inst: 'Level 9, 1 Martin Pl, Sydney NSW 2000, Australia',
		 result: 'LinkedIn Sydney, Level 9, 1 Martin Pl, Sydney NSW 2000' },
{ ref: 'SO101542', addr: 'The Paediatric Specialists, George Street, North Strathfield NSW, Australia', inst: '2/22 George St, North Strathfield NSW 2137, Australia',
		 result: 'The Paediatric Specialists, 2/22 George St, North Strathfield NSW 2137' },
{ ref: 'SO101538', addr: 'Mortlake Family Medical Practice, Tennyson Road, Mortlake NSW, Australia', inst: '32/88 Tennyson Rd, Mortlake NSW 2137, Australia',
		 result: 'Mortlake Family Medical Practice, 32/88 Tennyson Rd, Mortlake NSW 2137' },
{ ref: 'SO101532', addr: 'SBS, Herbert Street, Artarmon NSW, Australia', inst: '14 Herbert St, Artarmon NSW 2064, Australia',
		 result: 'SBS, 14 Herbert St, Artarmon NSW 2064' },
{ ref: 'SO101529', addr: "St Vincent's Private Hospital, Victoria Street, Darlinghurst NSW, Australia", inst: 'ROOM 842. 406 Victoria St, Darlinghurst NSW 2010, Australia',
		 result: "St Vincent's Private Hospital, ROOM 842. 406 Victoria St, Darlinghurst NSW 2010" },
{ ref: 'SO101527', addr: 'Sparke Helmore Lawyers, Martin Place, Sydney NSW, Australia', inst: '29/19 Martin Pl, Sydney NSW 2000, Australia',
		 result: 'Sparke Helmore Lawyers, 29/19 Martin Pl, Sydney NSW 2000' },
{ ref: 'SO101526', addr: 'usual suspects creative, Flinders Street, Surry Hills NSW, Australia', inst: '111 Flinders St, Surry Hills NSW 2010, Australia',
		 result: 'usual suspects creative, 111 Flinders St, Surry Hills NSW 2010' },
{ ref: 'SO101523', addr: "Barry's Bootcamp Martin Place, Elizabeth Street, Sydney NSW, Australia", inst: '52 Martin Place enter through 20 Elizabeth St, Sydney NSW 2000, Australia',
		 result: "Barry's Bootcamp Martin Pl, 52 Martin Pl enter through 20 Elizabeth St, Sydney NSW 2000" },
{ ref: 'SO101522', addr: 'APN Outdoor, Saunders Street, Pyrmont NSW, Australia', inst: '4/33 Saunders St, Pyrmont NSW 2009, Australia',
		 result: 'APN Outdoor, 4/33 Saunders St, Pyrmont NSW 2009' },
{ ref: 'SO101518', addr: 'Quay Appointments Ltd, George Street, Sydney NSW, Australia', inst: 'Level 38, 259 George St, Sydney NSW 2000, Australia',
		 result: 'Quay Appointments Ltd, Level 38, 259 George St, Sydney NSW 2000' },
{ ref: 'SO101503', addr: 'Bronte Medical Centre, Macpherson Street, Bronte NSW, Australia', inst: '133-135 Macpherson St, Bronte NSW 2024, Australia',
		 result: 'Bronte Medical Centre, 133-135 Macpherson St, Bronte NSW 2024' },
{ ref: 'SO101473', addr: 'Yardi Systems, Kent Street, Sydney NSW, Australia', inst: '23/207 Kent St, Sydney NSW 2000, Australia',
		 result: 'Yardi Systems, 23/207 Kent St, Sydney NSW 2000' },
{ ref: 'SO101466', addr: 'Bear Cottage, Fairy Bower Road, Manly NSW, Australia', inst: '2 Fairy Bower Rd, Manly NSW 2095, Australia',
		 result: 'Bear Cottage, 2 Fairy Bower Rd, Manly NSW 2095' },
{ ref: 'SO101459', addr: 'Corrs Chambers Westgarth, Chifley Square, Sydney NSW, Australia', inst: 'Level 17, 8 Chifley, 8/12 Chifley Square, Sydney NSW 2000, Australia',
		 result: 'Corrs Chambers Westgarth, Level 17, 8 Chifley, 8/12 Chifley Square, Sydney NSW 2000' },
{ ref: 'SO101447', addr: 'Pigdon Norgate Family Lawyers (Sydney Office), Berry Street, North Sydney NSW, Australia', inst: '8, 50 Berry St, North Sydney NSW 2060, Australia',
		 result: 'Pigdon Norgate Family Lawyers (Sydney Office), 8, 50 Berry St, North Sydney NSW 2060' },
{ ref: 'SO101440', addr: 'McAuley Catholic Primary School, Carlisle Street, Rose Bay NSW, Australia', inst: '8 Carlisle St, Rose Bay NSW 2029, Australia',
		 result: 'McAuley Catholic Primary School, 8 Carlisle St, Rose Bay NSW 2029' },
{ ref: 'SO101410', addr: 'Royal Prince Alfred Hospital, Missenden Road, Camperdown NSW, Australia', inst: '50 Missenden Rd, Camperdown NSW 2050, Australia',
		 result: 'Royal Prince Alfred Hospital, 50 Missenden Rd, Camperdown NSW 2050' },
{ ref: 'SO101409', addr: 'Quay West Suites Sydney Hotel, Gloucester Street, The Rocks NSW, Australia', inst: '98 Gloucester St, The Rocks NSW 2000, Australia',
		 result: 'Quay West Suites Sydney Hotel, 98 Gloucester St, The Rocks NSW 2000' },
{ ref: 'SO101396', addr: 'Cerner, Pacific Highway, North Sydney NSW, Australia', inst: '14/1 Pacific Hwy, North Sydney NSW 2060, Australia',
		 result: 'Cerner, 14/1 Pacific Hwy, North Sydney NSW 2060' },
{ ref: 'SO101395', addr: 'Ellerston Capital Limited, Sydney NSW, Australia', inst: 'Level 11,179 Elizabeth Street, Sydney NSW 2000, Australia',
		 result: 'Ellerston Capital Limited, Level 11,179 Elizabeth St, Sydney NSW 2000' },
{ ref: 'SO101374', addr: 'FCM Travel Solutions, Miller Street, North Sydney NSW, Australia', inst: '5, 60 Miller St, North Sydney NSW 2060, Australia',
		 result: 'FCM Travel Solutions, 5, 60 Miller St, North Sydney NSW 2060' },
{ ref: 'SO101367', addr: 'Royal Prince Alfred Hospital, Missenden Road, Camperdown NSW, Australia', inst: 'Neonatal Department, 50 Missenden Rd, Camperdown NSW 2050, Australia',
		 result: 'Royal Prince Alfred Hospital, Neonatal Department, 50 Missenden Rd, Camperdown NSW 2050' },
{ ref: 'SO101362', addr: 'Ason Group, George Street, Sydney NSW, Australia', inst: 'Suite 1202/220 George St, Sydney NSW 2000, Australia',
		 result: 'Ason Group, Suite 1202/220 George St, Sydney NSW 2000' },
{ ref: 'SO101361', addr: 'IFM Investors, Pitt Street, Sydney NSW, Australia', inst: '2/50 Pitt St, Sydney NSW 2000, Australia',
		 result: 'IFM Investors, 2/50 Pitt St, Sydney NSW 2000' },
{ ref: 'SO101360', addr: 'Suspension Espresso, Beaumont Street, Islington NSW, Australia', inst: '3 Beaumont St, Islington NSW 2296, Australia',
		 result: 'Suspension Espresso, 3 Beaumont St, Islington NSW 2296' },
{ ref: 'SO101338', addr: 'Intrec Management, Reserve Road, Artarmon NSW, Australia', inst: '73 Reserve Rd, Artarmon NSW 2064, Australia',
		 result: 'Intrec Management, 73 Reserve Rd, Artarmon NSW 2064' },
{ ref: 'SO101335', addr: 'ABC Ultimo Centre, Harris Street, Ultimo NSW, Australia', inst: 'ABC Ultimo Centre, 700 Harris St, Ultimo NSW 2007, Australia',
		 result: 'ABC Ultimo Centre, 700 Harris St, Ultimo NSW 2007' },
{ ref: 'SO101325', addr: 'Australian Red Cross, 464 Kent Street, Sydney NSW, Australia', inst: '4, 464 Kent St, Sydney NSW 2000, Australia',
		 result: 'Australian Red Cross, 4, 464 Kent St, Sydney NSW 2000' },
{ ref: 'SO101322', addr: 'Art Gallery of New South Wales, Art Gallery Road, Sydney NSW, Australia', inst: 'Art Gallery Rd, Sydney NSW 2000, Australia',
		 result: 'Art Gallery of New South Wales, Art Gallery Rd, Sydney NSW 2000' },
{ ref: 'SO101321', addr: 'NSW Electoral Commission, Kent Street, Sydney NSW, Australia', inst: 'level 25/201 Kent St, Sydney NSW 2218, Australia',
		 result: 'NSW Electoral Commission, level 25/201 Kent St, Sydney NSW 2218' },
{ ref: 'SO101317', addr: 'Scholastic Australia, Pacific Highway, Lindfield NSW, Australia', inst: 'Suite 101, Level 1, 345 Pacific Hwy, Lindfield NSW 2070, Australia',
		 result: 'Scholastic Australia, Suite 101, Level 1, 345 Pacific Hwy, Lindfield NSW 2070' },
{ ref: 'SO101310', addr: 'Royal North Shore Hospital, Reserve Rd, St Leonards NSW, Australia', inst: 'St Leonards NSW 2065, Australia',
		 result: 'Royal North Shore Hospital, Reserve Rd, St Leonards NSW 2065' },
{ ref: 'SO101289', addr: 'Cisco, Pacific Highway, North Sydney NSW, Australia', inst: '24/177 Pacific Hwy, North Sydney NSW 2060, Australia',
		 result: 'Cisco, 24/177 Pacific Hwy, North Sydney NSW 2060' },
{ ref: 'SO101288', addr: '32 Pyrmont Bridge Rd, Pyrmont NSW 2009, Australia', inst: 'OMD Australia',
		 result: '32 Pyrmont Bridge Rd, Pyrmont NSW 2009' },
{ ref: 'SO101276', addr: 'SHOWPO, Clarence Street, Sydney NSW, Australia', inst: '3/156 Clarence St, Sydney NSW 2000, Australia',
		 result: 'SHOWPO, 3/156 Clarence St, Sydney NSW 2000' },
{ ref: 'SO101273', addr: 'Carat Australia, 26 Hickson Rd, Sydney NSW 2000, Australia', inst: '3, 26 Hickson Rd, Sydney NSW 2000, Australia',
		 result: 'Carat Australia, 3, 26 Hickson Rd, Sydney NSW 2000' },
{ ref: 'SO101265', addr: 'Killara High School, Koola Ave, East Killara NSW, Australia', inst: 'East Killara NSW 2071, Australia',
		 result: 'Killara High School, Koola Ave, East Killara NSW 2071' },
{ ref: 'SO101263', addr: "St Augustine's College - Sydney, Federal Parade, Brookvale NSW, Australia", inst: 'Federal Parade, Brookvale NSW 2100, Australia',
		 result: "St Augustine's College - Sydney, Federal Parade, Brookvale NSW 2100" },
{ ref: 'SO101255', addr: 'News Corp Australia, 2 Holt Street, Surry Hills NSW, Australia', inst: '2 Holt St, Surry Hills NSW 2010, Australia',
		 result: 'News Corp Australia, 2 Holt St, Surry Hills NSW 2010' },
{ ref: 'SO101248', addr: 'Australian Broadcasting Corporation, Harris Street, Ultimo NSW, Australia', inst: '700 Harris St, Ultimo NSW 2007, Australia',
		 result: 'Australian Broadcasting Corporation, 700 Harris St, Ultimo NSW 2007' },
{ ref: 'SO101245', addr: 'Procter & Gamble Australia Pty Ltd, Innovation Road, Macquarie Park NSW, Australia', inst: 'Level 4, 1 Innovation Rd, Macquarie Park NSW 2113, Australia',
		 result: 'Procter & Gamble Australia Pty Ltd, Level 4, 1 Innovation Rd, Macquarie Park NSW 2113' },
{ ref: 'SO101214', addr: 'Seymour Centre Stage Door, Blackwattle Creek Lane, Chippendale NSW, Australia', inst: 'Blackwattle Creek Ln, Chippendale NSW 2008, Australia',
		 result: 'Seymour Centre Stage Door, Blackwattle Creek Ln, Chippendale NSW 2008' },
{ ref: 'SO101211', addr: 'Royal Prince Alfred Hospital, Missenden Road, Camperdown NSW, Australia', inst: '50 Missenden Rd, Camperdown NSW 2050, Australia',
		 result: 'Royal Prince Alfred Hospital, 50 Missenden Rd, Camperdown NSW 2050' },
{ ref: 'SO101204', addr: "dusk Australasia Pty Ltd, O'Riordan Street, Alexandria NSW, Australia", inst: "75/85 O'Riordan St, Alexandria NSW 2015, Australia",
		 result: "dusk Australasia Pty Ltd, 75/85 O'Riordan St, Alexandria NSW 2015" },
{ ref: 'SO101201', addr: 'Glen Street Theatre, Blackbutts Road, Belrose NSW, Australia', inst: 'Cnr Glen Street, Blackbutts Rd, Belrose NSW 2085, Australia',
		 result: 'Glen St Theatre, Cnr Glen St, Blackbutts Rd, Belrose NSW 2085' },
{ ref: 'SO101177', addr: 'COSMAX PRESTIGE BRANDS PTY LTD, Beauchamp Road, Banksmeadow NSW, Australia', inst: '13/2 Beauchamp Rd, Banksmeadow NSW 2019, Australia',
		 result: 'COSMAX PRESTIGE BRANDS PTY LTD, 13/2 Beauchamp Rd, Banksmeadow NSW 2019' },
{ ref: 'SO101161', addr: 'Wavemaker Sydney, Berry Street, North Sydney NSW, Australia', inst: '14/65 Berry St, North Sydney NSW 2060, Australia',
		 result: 'Wavemaker Sydney, 14/65 Berry St, North Sydney NSW 2060' },
{ ref: 'SO101155', addr: 'Only About Children Enmore, Edgeware Road, Newtown NSW, Australia', inst: '290 Edgeware Rd, Newtown NSW 2042, Australia',
		 result: 'Only About Children Enmore, 290 Edgeware Rd, Newtown NSW 2042' },
{ ref: 'SO101154', addr: 'Sydney Adventist Hospital, Fox Valley Road, Wahroonga NSW, Australia', inst: 'Clark Tower Level 8, room 31, 185 Fox Valley Rd, Wahroonga NSW 2076 , Australia',
		 result: 'Sydney Adventist Hospital, Clark Tower Level 8, room 31, 185 Fox Valley Rd, Wahroonga NSW 2076 ' },
{ ref: 'SO101145', addr: 'Royal Rehab, Morrison Road, Ryde NSW, Australia', inst: '235 Morrison Rd, Ryde NSW 2112, Australia',
		 result: 'Royal Rehab, 235 Morrison Rd, Ryde NSW 2112' },
{ ref: 'SO101143', addr: 'Wenona School, Walker Street, North Sydney NSW, Australia', inst: 'Principals Office. 176 Walker St, North Sydney NSW 2060, Australia',
		 result: 'Wenona School, Principals Office. 176 Walker St, North Sydney NSW 2060' },
{ ref: 'SO101142', addr: 'Redkite, Elizabeth Street, Surry Hills NSW, Australia', inst: '3/418a Elizabeth St, Surry Hills NSW 2010, Australia',
		 result: 'Redkite, 3/418a Elizabeth St, Surry Hills NSW 2010' },
{ ref: 'SO101129', addr: 'IBM, St Leonards NSW, Australia', inst: 'Level 13,IBM Centre,601 Pacific Hwy, St Leonards NSW 2065, Australia',
		 result: 'Level 13,IBM Centre,601 Pacific Hwy, St Leonards NSW 2065' },
{ ref: 'SO101120', addr: 'Think Childcare Limited, Park Avenue, Drummoyne NSW, Australia', inst: '3/1 Park Ave, Drummoyne NSW 2047, Australia',
		 result: 'Think Childcare Limited, 3/1 Park Ave, Drummoyne NSW 2047' },
{ ref: 'SO101118', addr: "Carroll & O'Dea Lawyers Sydney, Elizabeth Street, Sydney NSW, Australia", inst: 'St James Centre, Level 18 111/99 Elizabeth St, Sydney NSW 2000, Australia',
		 result: "Carroll & O'Dea Lawyers Sydney, St James Centre, Level 18 111/99 Elizabeth St, Sydney NSW 2000" },
{ ref: 'SO101116', addr: 'Academy Xi Sydney, Druitt Street, Sydney NSW, Australia', inst: 'Ground floor/48 Druitt St, Sydney NSW 2000, Australia',
		 result: 'Academy Xi Sydney, Ground floor/48 Druitt St, Sydney NSW 2000' },
{ ref: 'SO101114', addr: 'Trans - Tasman Business Circle, Oxford Street, Bondi Junction NSW, Australia', inst: '802/251 Oxford St, Bondi Junction NSW 2022, Australia',
		 result: 'Trans - Tasman Business Circle, 802/251 Oxford St, Bondi Junction NSW 2022' },
{ ref: 'SO101109', addr: 'Crone Architects, George Street, Sydney NSW, Australia', inst: 'Level 18/680 George St, Sydney NSW 2000, Australia',
		 result: 'Crone Architects, Level 18/680 George St, Sydney NSW 2000' },
{ ref: 'SO101104', addr: 'North Shore Private Hospital, Westbourne Street, St Leonards NSW, Australia', inst: 'Westbourne St, St Leonards NSW 2065, Australia',
		 result: 'North Shore Private Hospital, Westbourne St, St Leonards NSW 2065' },
{ ref: 'SO101102', addr: 'IMF Bentham, Pitt Street, Sydney NSW, Australia', inst: 'Level 10, 68 Pitt St, Sydney NSW 2000, Australia',
		 result: 'IMF Bentham, Level 10, 68 Pitt St, Sydney NSW 2000' },
{ ref: 'SO101101', addr: 'Canon Australia, Talavera Road, Macquarie Park NSW, Australia', inst: 'A, The Park Estate, 5 Talavera Rd, Macquarie Park NSW 2113, Australia',
		 result: 'Canon Australia, A, The Park Estate, 5 Talavera Rd, Macquarie Park NSW 2113' },
{ ref: 'SO101078', addr: 'Denwol Group, Greek Street, Glebe NSW, Australia', inst: '49 Greek St, Glebe NSW 2037, Australia',
		 result: 'Denwol Group, 49 Greek St, Glebe NSW 2037' },
{ ref: 'SO101077', addr: 'Anzac Park Public School, Anzac Avenue, Cammeray NSW, Australia', inst: '2 Anzac Ave, Cammeray NSW 2062, Australia',
		 result: 'Anzac Park Public School, 2 Anzac Ave, Cammeray NSW 2062' },
{ ref: 'SO101075', addr: 'Redkite, Elizabeth Street, Surry Hills NSW, Australia', inst: '3/418a Elizabeth St, Surry Hills NSW 2010, Australia',
		 result: 'Redkite, 3/418a Elizabeth St, Surry Hills NSW 2010' },
{ ref: 'SO101074', addr: 'Bliss Early Learning, 55 Pyrmont Bridge Road, Pyrmont NSW, Australia', inst: '55 Pyrmont Bridge Rd, Pyrmont NSW 2009, Australia',
		 result: 'Bliss Early Learning, 55 Pyrmont Bridge Rd, Pyrmont NSW 2009' },
];

describe('fetch/odooParseAddress.js Unit tests', () => {
	it('should pass a test', () => {
		true.should.equal(true);
    });
    
    test_data.forEach(data => {
        it(`should process address ${data.ref}`, () => {
            odooParseShipAddress(data.addr, data.inst).addr.should.equal(data.result);
        })
    })

});
